name: Static_Code_Analysis

on:
  push:
    branches: [ testing_file ]
  pull_request:
    branches: [ testing_file ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install cppcheck
      run: sudo apt -y install cppcheck
    - name: cpp Check
      run: cppcheck 3_Implementation
